# # cspell:ignore cmdline, workdir
---
ansible-navigator:
  ansible:
    config:
      path: ./ansible.cfg

  execution-environment:
    container-engine: podman
    image: aap2.example.com/ee-supported-rhel8:latest
    pull:
      arguments:
        - "--tls-verify=false"
      policy: missing

  logging:
    level: critical

  mode: stdout

  playbook-artifact:
    enable: False

