---
- name: Get the version of softwares
  hosts: all
  gather_facts: false
  tasks:
    - name: Get the version of avalable application
      ansible.builtin.uri:
        url: "http://{{ item.value.host }}:{{item.value.port}}/version.html"
        return_content: true
      register: versioninfo
      delegate_to: localhost
      failed_when: versioninfo is failed #or "'version:' not in versioninfo.content"
      loop: "{{lookup('ansible.builtin.dict',app)}}"    

    #- ansible.builtin.debug:
    #    msg: "{{versioninfo.results}}"

  #  - debug: 
  #      msg: "{{ item }}" 
  #    loop: "{{ versioninfo.results|map(attribute='url')|list}}"


  #  - debug: 
  #      msg: "{{ item }}"
  #    loop: "{{ versioninfo.results|map(attribute='content')|list}}"

    - name: create a dir in tmp
      ansible.builtin.file:
        path: /tmp/app
        owner: root
        group: root
        mode: '0755'
        state: directory
      delegate_to: localhost

    - name: render template
      ansible.builtin.template:
        src: display.j2
        dest: /tmp/app/version_info-{{inventory_hostname}}.csv
      delegate_to: localhost

#    - debug: 
#        msg: "{{ item['item']['key'] }}"
#      loop: "{{ versioninfo.results|list}}"
#
    - name: Assemble from fragments from a directory
      ansible.builtin.assemble:
        src: /tmp/app
        dest: /tmp/mysql_app.txt
      delegate_to: localhost

    - name: Read users from CSV file and return a list
      community.general.read_csv:
        path: /tmp/mysql_app.txt
        fieldnames: host,application,version
        delimiter: ','
      register: appdata
      delegate_to: localhost

    - set_fact:
        db_database: version_data
        db_host: 192.168.1.18
        db_user: root
        db_password: root

    - debug:
        msg: "{{ appdata }}"
 
    - name: Removing older data of versions from DB {{ db_database }} 
      community.mysql.mysql_query:
         login_host: "{{ db_host }}"
         login_db: "{{ db_database }}"
         login_user: "{{ db_user }}"
         login_password: "{{ db_password }}"
         query:
           - TRUNCATE TABLE appversion; 
      delegate_to: localhost

    - name: Loading new data by Running several insert queries against db {{ db_database }} 
      community.mysql.mysql_query:
         login_host: "{{ db_host }}"
         login_db: "{{ db_database }}"
         login_user: "{{ db_user }}"
         login_password: "{{ db_password }}"
         query:
           - INSERT INTO appversion (host, application,Unique_instance ,version, Date) VALUES ("{{item.host}}","{{item.application}}","{{item.host}}-{{item.application}}","{{item.version}}" ,now())
      loop: "{{ appdata.list }}"
      ignore_errors: true
      register: querystatus
      delegate_to: localhost


      
