---
- name: reder a grafana grafana_dashboard
  hosts: localhost
  connection: local    
  tasks:
  #  - set_fact:
  #      db_database: 
  #      db_host: 
  #      db_user: 
  #      db_password: 

    - name: run a select query to get the list of panel we want to papulate
      community.mysql.mysql_query:
        login_host: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:db_host') }}"
        login_db: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:db_database') }}"
        login_user: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:db_user') }}"
        login_password: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:password') }}"
        query:
          - select application from version_data.appversion;         
        single_transaction: yes
      register: app_db_query     

#    - debug:
#        var: app_db_query

    - name: Render Grafana json for grafana Dashboard. 
      ansible.builtin.template:
        src: dash.json.j2
        dest: /tmp/dash.json

    - name: Import Grafana dashboard New_DashBoard with newly build json
      community.grafana.grafana_dashboard:
        grafana_url: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:url') }}"
        grafana_api_key: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:key') }}"
        state: present
        commit_message: Updated by ansible
        overwrite: true
        path: /tmp/dash.json

        
