---
- name: reder a grafana grafana_dashboard
  hosts: localhost
  connection: local    
  tasks:

    - name: run a select query to get the list of panel we want to papulate
      community.mysql.mysql_query:
        login_host: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:db_host') }}"
        login_db: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:db_database') }}"
        login_user: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:db_user') }}"
        login_password: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:db_password') }}"
        query:
          - select application from version_data.appversion ORDER BY app ASC;         
        single_transaction: yes
      register: app_db_query     

    - name: Render Grafana json for grafana Dashboard. 
      ansible.builtin.template:
        src: dash.json.j2
        dest: /tmp/dash.json
        owner: root
        group: root
        mode: 0644

    - name: Import Grafana dashboard New_DashBoard with newly build json
      community.grafana.grafana_dashboard:
        grafana_url: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:url') }}"
        grafana_api_key: "{{ lookup('hashi_vault', 'secret=secret/data/dev/grafana:key') }}"
        state: present
        commit_message: Updated by ansible
        overwrite: true
        path: /tmp/dash.json

        
