---
- name: reder a grafana grafana_dashboard
  hosts: localhost
  connection: local    
  tasks:
  #  - set_fact:
  #      db_database: 
  #      db_host: 
  #      db_user: 
  #      db_password: 

    - name: run a select query to get the list of panel we want to papulate
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_db: "{{ db_database }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        query:
          - select application from version_data.appversion;         
        single_transaction: yes
      register: app_db_query     

#    - debug:
#        var: app_db_query

    - name: Render Grafana json for grafana Dashboard. 
      ansible.builtin.template:
        src: dash.json.j2
        dest: /tmp/dash.json

    - name: Import Grafana dashboard New_DashBoard with newly build json
      community.grafana.grafana_dashboard:
        grafana_url: "{{grafana_URL}}""
        grafana_api_key: "{{grafana_key}}"
        state: present
        commit_message: Updated by ansible
        overwrite: true
        path: /tmp/dash.json

        
