- name: Container testing
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /data
        state: directory
        mode: '0755'        

    - name: Create a directory for an applications
      ansible.builtin.file:
        path: "/data/{{ item.value.name }}"
        state: directory
        mode: '0755'
      loop: "{{lookup('ansible.builtin.dict',app)}}" 

    - name: Genrate the sample version file
      ansible.builtin.template:
        src: version.j2
        dest: "/data/{{ item.value.name }}/version.html"
      loop: "{{lookup('ansible.builtin.dict',app)}}"
     
    - name: Include selinux role
      vars:
        selinux_fcontexts:
          - {target: '/data/{{ item.value.name }}(/.*)?', setype: 'httpd_sys_content_t', state: 'present'}
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.selinux
      loop: "{{lookup('ansible.builtin.dict',app)}}"  

    - name: launch a container
      containers.podman.podman_container:
        name: "nginx_container_{{ item.value.name }}"
        image: docker.io/nginx:stable-alpine3.17-slim
        state: started
        ports:
          - "{{item.value.port}}:80"
        volumes:
          - "/data/{{ item.value.name }}:/usr/share/nginx/html:Z"
        recreate: true
      loop: "{{lookup('ansible.builtin.dict',app)}}"  


    - name: Create HTML report
      ansible.builtin.template:
        src: report.j2
        dest: "/data/{{ item.value.name }}/index.html"
        mode: "644"
      loop: "{{lookup('ansible.builtin.dict',app)}}"  

    - name: Copy CSS over
      ansible.builtin.copy:
        src: "css"
        dest: "/data/{{ item.value.name }}"
        directory_mode: true
        mode: "775"
      loop: "{{lookup('ansible.builtin.dict',app)}}"

    - name: Copy CSS over
      ansible.builtin.copy:
        src: "{{ item[1] }}"
        dest: "/data/{{ item[0].value.name }}"
        directory_mode: true
        mode: "644"
      loop: "{{ lookup('ansible.builtin.dict',app) | product(['webpage_logo.png','redhat-ansible-logo.svg']) | list}}" 

    - name: Make sure firewall is up and running 
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow traffic so our application can take traffic
      ansible.posix.firewalld:
        port: "{{ item.value.port }}/tcp"
        permanent: true
        state: enabled
      loop: "{{lookup('ansible.builtin.dict',app)}}" 

##### This was written for Testing #####
  #  - name: Gather facts for all containers
  #    containers.podman.podman_container_info:
  #    register: info
    
  #  - debug:
  #      msg: "{{item.Name}}"
  #    loop: "{{info.containers}}" 


#    - debug:
#        msg: "{{hostvars[inventory_hostname]['app']|map(attribute='name')|list}}"

#    - debug:
#        msg: "{{item}}"
#      loop: "{{ hostvars[inventory_hostname]['app']|map(attribute='version')|list}}"  
